name: CI Validation

on:
  pull_request:
    branches:
      - main
      - stg

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm ci

      - name: Validate Docker Build
        run: docker compose build
